#!/bin/sh

GIT_WORK_TREE="$(cd "$(dirname "$0")" && pwd)"
GIT_DIR="$GIT_WORK_TREE/.git"

if ! test -d "$HOME" ; then
  echo "Can't read \$HOME directory '$HOME'!" >&2
  exit 2
fi

if ! test -d "$GIT_DIR" ; then
  echo "Can't read git repository at '$GIT_DIR'!" >&2
  exit 2
fi

if ! test -d "$GIT_WORK_TREE" ; then
  echo "Can't read git work tree at '$GIT_WORK_TREE'!" >&2
  exit 2
fi

export HOME GIT_DIR GIT_WORK_TREE

INDEX_FMT='%o %040s\t%s\n'
PATHS=(
  "dot/:$HOME/."
  "completion/:/usr/local/etc/bash_completion.d/"
)

for prefix in "${PATHS[@]}" ; do
  git ls-files -s "${prefix%%:*}" | while read mode hash n path ; do
    p="${prefix#*:}${path#${prefix%%:*}}"
    if test -f "$p" ; then
      m="$(stat -f '%p' "$p")"
      h="$(git hash-object -w -t blob --path="$path" "$p")"
      if ! test "x$h" = "x$hash" -a "x$m" = "x$mode" ; then
        printf "$INDEX_FMT" "$m" "$h" "$path"
      fi
    else
      printf "$INDEX_FMT" 0 0 "$path"
    fi
  done
done | git update-index --index-info
