#!/bin/sh

# Easier navigation: .., ..., ~ and -
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ~="cd ~"
alias -- -="cd -"

# be nice
alias please=sudo

# Detect which `ls` flavor is in use
if ls --color > /dev/null 2>&1; then # GNU `ls`
	__colorflag="--color=auto"
elif ls -G > /dev/null 2>&1; then # OS X `ls`
	__colorflag="-G"
fi
if test -n "${__colorflag}" ; then
  alias ls="ls ${__colorflag}"
  alias ll="ls -l ${__colorflag}"
  alias la="ls -la ${__colorflag}"
fi
unset __colorflag

# OS X has no `md5sum`, so use `md5` as a fallback
type -t md5sum > /dev/null || alias md5sum="md5"

# Hide/show all desktop icons (useful when presenting)
alias hidedesktop="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"
alias showdesktop="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"

# One of @janmoesen’s ProTip™s
for method in GET HEAD POST PUT DELETE TRACE OPTIONS; do
	alias "$method"="lwp-request -m '$method'"
done

json () { 
  ( echo "var sys = require('sys');"
    echo "var obj = $(cat);"
    echo "sys.puts(JSON.stringify(obj$1));" ) | node
}
