#!/bin/sh

if test -x `which defaults 2>/dev/null` ; then
  _locale=`defaults read "NSGlobalDomain" "AppleLocale"`
  if locale -a | grep -q "$_locale" ; then
    LANG="$_locale.UTF-8"
  else
    LANG="en_US.UTF-8"
  fi
  export LANG
  unset _locale
elif test -x `which xprop 2>/dev/null` ; then
  _locale=`xprop -id $WINDOWID -f WM_LOCALE_NAME 8s -notype WM_LOCALE_NAME 2>/dev/null | \
           sed 's/WM_LOCALE_NAME = "\(.*\)"/\1/p;d'`

  if test -n "$_locale" ; then
    LANG="$_locale"
    export LANG
  fi
  unset _locale
fi
